name: ALPAC
favicon: null
layout_spectrum: 0.75434
typography_spectrum: 0.75626
title: 'ALPAC - Austrian Lobbying & Public Affairs Council'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b291d'
    - '#f4f2e5'
    - '#636456'
    - '#99937d'
    - '#c0b894'
  brandStrength: 0
  lightness: 0.741485099773854
  saturation: 0.9017147871199995
  rhythmicContrast: 0.9069219753146172
purpose: []
