typography_spectrum: 0.25337
color:
  brandColors:
    - '#ffffff'
    - '#008dca'
    - '#000000'
    - '#474747'
    - '#74c2e4'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74895
analytics:
  google: null
  facebook: null
  twitter: null
name: ALPAC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Unternehmensliste
    id: b2e54a83-80cd-4368-884f-a0f1542f1100
    type: content
  - name: Verhaltenskodex
    id: c676c83b-8ea6-4e05-8bed-9eeac1830a02
    type: content
  - name: 'Qualitätskriterien '
    id: c584ffe7-2bda-4396-b186-9cc1d5d01865
    type: content
  - name: Compliance Management
    id: 5cccc5a7-daa4-428c-9ac4-626fbffd1a41
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ALPAC
description: ''
purpose: []
