name: ALPAC
favicon: null
layout_spectrum: 0.49615
typography_spectrum: 0.74277
title: Austrian Leading Public Affairs Consultancies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#008dca'
    - '#000000'
    - '#474747'
    - '#74c2e4'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.9017147871199995
  rhythmicContrast: 0.75
purpose: []
