name: ALPAC
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.50193
title: 'ALPAC - Austrian Lobbying & Public Affairs Council'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#008dca'
    - '#000000'
    - '#474747'
    - '#74c2e4'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.9017147871199995
  rhythmicContrast: 0.9069219753146172
purpose: []
